### ISSUE TITLE
list_datasets() throws malformed JSON

### ISSUE THREAD

**Issue by vjcitn** [BiocPy/scrnaseq#17]
Python 3.10.12 (main, Sep 11 2024, 15:47:36) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import scrnaseq
>>> datasets = scrnaseq.list_datasets()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/scrnaseq/list_datasets.py", line 61, in list_datasets
    _qresults = conn.execute(stmt).fetchall()
sqlite3.OperationalError: malformed JSON

**Comment by jkanche** [comment]
This is an issue with the `sqlite3` library shipped by default, it needs an update. I do this on gothub actions as well, for ref: https://github.com/BiocPy/scrnaseq/blob/master/.github/workflows/pypi-publish.yml#L28

**Comment by vjcitn** [comment]
In all likelihood this issue can be closed, but I can tell you that working within a container using python 3.10 I have gotten nowhere, with the new sqlite installation noted in the action, same error.  I see that the action uses python 3.9 -- is this essential?

**Comment by vjcitn** [comment]
works fine on mac with python 3.12 ... debian/ubuntu snafu.  sorry for the noise.

**Comment by jkanche** [comment]
The test action runs on multiple python versions from 3.9-3.12 - https://github.com/BiocPy/scrnaseq/actions/runs/10998486432.

I ran into this only on linux, not on macos, and updating sqlite3 has resolved this.

**Comment by jkanche** [comment]
oops, i guess we posted at the same time. all good.
